#!/usr/bin/perl

# turns 231x148 P4 pgm image into C64 Newsroom photo
#
# (c)2023 cameron kaiser. all rights reserved. bsd license.
#
# known bugs:
# - this is the only size supported

use bytes; # remove for 5.005
undef $/;
while(<>) { $buf .= $_; }

die("expected 231x148 P4 PGM\n") if(substr($buf, 0, 11) ne "P4\n231 148\n");
$buf = unpack("H*", substr($buf, 11)); # avoid any irregularities
die("insufficient bytes remain: need 4292\n") if length($buf) < 8584;
warn("more than 4292 bytes: remainder truncated\n") if length($buf) != 8584;

select(STDOUT); $|++;
print STDOUT pack("H*", "00a0c41014a708ee00ff"); # standard header

# read and convert bytes until no more to convert
$byc = 0;
for($i=0; $i<8584; $i+=2) {
	$v = hex(substr($buf, $i, 2));

	# invert: newsroom white is on, pbm black is on
	$v ^= 255; # invert

	# newsroom and pbm are both big endian left
	print STDOUT pack("C", $v);
}

